### Package Imports

In [2]:
import numpy as np

# Assignment 1: Array Basics

Hi there,

Can you import Numpy and convert the following list comprehension (I just learned about comprehensions in an awesome course by Maven) into an array?

Once you've done that report the following about the array:
* The number of dimensions 
* The shape
* The number of elements in the array
* The type of data contained inside

In [23]:
my_list = [x * 10 for x in range(1, 11)]
a = np.array(my_list).reshape(5,2)

In [24]:
a

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [16]:
a.shape

(10, 1)

In [11]:
a.ndim

1

In [18]:
a.size

10

In [19]:
a.dtype

dtype('int32')

# Assignment 2: Array Creation

Thanks for your help with the first piece - I'm starting to understand some of the key differences between base Python data types and NumPy arrays. 

Does NumPy have anything like the range() function from base Python?

If so: 
* create the same array from assignment 1 using a NumPy function. 
* Make it 5 rows and 2 columns. 
* It's ok if the datatype is float or int.

In [31]:
b = np.arange(0,101, 10)
b

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [28]:
c = b.reshape(5,2)
c

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [41]:
c = np.linspace(1,101,100).reshape(10,10)
c

array([[  1.        ,   2.01010101,   3.02020202,   4.03030303,
          5.04040404,   6.05050505,   7.06060606,   8.07070707,
          9.08080808,  10.09090909],
       [ 11.1010101 ,  12.11111111,  13.12121212,  14.13131313,
         15.14141414,  16.15151515,  17.16161616,  18.17171717,
         19.18181818,  20.19191919],
       [ 21.2020202 ,  22.21212121,  23.22222222,  24.23232323,
         25.24242424,  26.25252525,  27.26262626,  28.27272727,
         29.28282828,  30.29292929],
       [ 31.3030303 ,  32.31313131,  33.32323232,  34.33333333,
         35.34343434,  36.35353535,  37.36363636,  38.37373737,
         39.38383838,  40.39393939],
       [ 41.4040404 ,  42.41414141,  43.42424242,  44.43434343,
         45.44444444,  46.45454545,  47.46464646,  48.47474747,
         49.48484848,  50.49494949],
       [ 51.50505051,  52.51515152,  53.52525253,  54.53535354,
         55.54545455,  56.55555556,  57.56565657,  58.57575758,
         59.58585859,  60.5959596 ],
       [ 6

In [46]:
c = np.linspace(10,100,11)
c

array([ 10.,  19.,  28.,  37.,  46.,  55.,  64.,  73.,  82.,  91., 100.])

Looking good so far! One of our data scientists asked about random number generation in NumPy.

Can you create a 3x3 array of random numbers between 0 and 1? Use a random state of 2022.

Store the random array in a variable called `random_array`.

In [3]:
rng = np.random.default_rng(2022)
d = rng.random(9).reshape(3,3)
d

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778],
       [0.1108689 , 0.04305584, 0.41441747]])

# Assignment 3: Accessing Array Data


Slice and index the `random_array` we created in the previous exercise. Perform the following:

* Grab the first two 'rows' of the array
* Grab the entire first column
* Finally, grab the second selement of the third row.

Thanks!


In [62]:
d[:2,:]

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778]])

In [64]:
d[:,0]

array([0.24742606, 0.06066207, 0.1108689 ])

In [58]:
d[2,1]

0.04305584439252108

In [60]:
d[:,0]

array([0.24742606, 0.06066207, 0.1108689 ])

# Assignment 4: Arithmetic Operations

The creativity of our marketing team knows no bounds!

They've asked us to come up with a simple algorithm to provide a random discount to our list of prices below. 

Before we do that, 

* Add a 5 dollar shipping fee to each price. Call this array `total`.

Once we have that, we want to use the random_array created in assignment 2 and apply them to the 6 prices.

* Grab the first 6 numbers from `random_array`, reshape it to one dimension. Call this `discount_pct`.
* Subtract `discount_pct` FROM 1, store this in `pct_owed`.
* Multiply `pct_owed` by `total` to get the final amount owed.

In [8]:
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])
total = prices + 5
total

array([ 10.99,  11.99,  27.49, 104.99,   9.99,  54.99])

In [9]:
d

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778],
       [0.1108689 , 0.04305584, 0.41441747]])

In [6]:
discount_pct = d[:2,:].reshape(6)



array([0.24742606, 0.09299006, 0.61176337, 0.06066207, 0.66103343,
       0.75515778])

In [11]:
pct_owed = 1 - discount_pct

In [17]:
final= (pct_owed*total).round(2)
final

array([ 8.27, 10.88, 10.67, 98.62,  3.39, 13.46])

# Assignment 5: Filtering Arrays

Filter the product array to only include those with prices greater than 25.

Modify your logic to include cola, despite it not having a price greater than 25. 
Store the elements returned in an array called `fancy_feast_special`.

Next, create a shipping cost array where the cost is 0 if price is greater than 20, and 5 if not. 

In [31]:
products = np.array(
    ["salad", "bread", "mustard", "rare tomato", "cola", "gourmet ice cream"]
)
products[prices > 25]


array(['rare tomato', 'gourmet ice cream'], dtype='<U17')

In [32]:
fancy_feast_special = products[(prices > 25) | (products == "cola")]
fancy_feast_special

array(['rare tomato', 'cola', 'gourmet ice cream'], dtype='<U17')

In [33]:
shipping =  np.where(prices > 20, 0, 5)
shipping

array([5, 5, 0, 0, 5, 0])

# Assignment 6: Aggregating and Sorting Arrays

First, grab the top 3 highest priced items in our list. 

Then, calculated the mean, min, max, and median of the top three prices.

Finally, calculate the number of unique price tiers in our `price_tiers` array.

In [45]:
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])
top3 = np.sort(prices)[-3:]
top3

array([22.49, 49.99, 99.99])

In [41]:
prices[-3:]

array([22.49, 49.99, 99.99])

In [48]:
print(f"Mean", np.mean(top3))
print(f"Min", np.min(top3))
print(f"Max",np.max(top3))
print(f"Median",np.median(top3))

Mean 57.49
Min 22.49
Max 99.99
Median 49.99


In [49]:
price_tiers = np.array(["budget", "budget", "mid-tier", "luxury", "mid-tier", "luxury"])
uni = np.unique(price_tiers)
uni

array(['budget', 'luxury', 'mid-tier'], dtype='<U8')

# Assignment 7: Bringing it All Together

Ok, final NumPy task - let's read in some data with the help of Pandas.

Our data scientist provided the code to read in a csv as a Pandas dataframe, and has converted the two columns of interest to arrays.

* Filter `sales_array` down to only sales where the product family was produce. 

* Then, randomly sample roughly half (random number < .5) of the produce sales and report the mean and median sales. Use a random seed of 2022.

* Finally, create a new array that has the values 'above_both', 'above_median', and 'below_both' based on whether the sales were above the median and mean of the sample, just above the median of the sample, or below both the median and mean of the sample. 

In [50]:
import pandas as pd
import numpy as np

retail_df = pd.read_csv(
    "../retail/retail_2016_2017.csv", skiprows=range(1, 11000), nrows=1000
)

family_array = np.array(retail_df["family"])
sales_array = np.array(retail_df["sales"])

In [69]:
produce_sale = sales_array[family_array == "PRODUCE"]


In [72]:
rng = np.random.default_rng(2022)

random_array = rng.random(30)
random_sales = produce_sale[random_array < 0.5]
print(f"Mean of the sales = " ,np.mean(random_sales))
print (f"Median of the sales = " , np.median(random_sales))


Mean of the sales =  2268.102470588235
Median of the sales =  1272.755


In [73]:

print( random_array < 0.5)

[ True  True False  True False False  True  True  True False False  True
 False  True  True False False False False False  True  True False False
  True  True  True  True  True  True]


In [74]:
print(random_array)

[0.24742606 0.09299006 0.61176337 0.06066207 0.66103343 0.75515778
 0.1108689  0.04305584 0.41441747 0.98862926 0.96919869 0.25697153
 0.55876211 0.24234798 0.32202029 0.89135975 0.94611366 0.72253931
 0.92847437 0.99608701 0.2494223  0.06229007 0.94479027 0.65028587
 0.32167568 0.08336384 0.21924361 0.08417791 0.05213927 0.20525022]


In [85]:
mask = np.where((random_sales > np.median(random_sales)) & (random_sales > np.mean(random_sales)), "above_both", 
                np.where(
                    random_sales > np.median(random_sales), "above_median", "below_both"
                        ) 
                    
                    
                )




In [86]:
mask

array(['above_median', 'below_both', 'below_both', 'below_both',
       'above_both', 'below_both', 'below_both', 'above_both',
       'below_both', 'below_both', 'above_both', 'above_both',
       'below_both', 'above_median', 'above_both', 'below_both',
       'above_both'], dtype='<U12')

In [89]:
np.where(
    random_sales < np.median(random_sales), "below_both", np.where(
        random_sales < np.mean(random_sales), "above_median", "above_both"
    )    
)

        

array(['above_median', 'below_both', 'below_both', 'below_both',
       'above_both', 'below_both', 'below_both', 'above_both',
       'below_both', 'above_median', 'above_both', 'above_both',
       'below_both', 'above_median', 'above_both', 'below_both',
       'above_both'], dtype='<U12')

In [90]:
random_sales

array([1662.394,  447.064,  962.866, 1077.44 , 3404.531,  962.96 ,
       1089.319, 7860.031,  446.038, 1272.755, 2775.771, 2339.906,
        722.333, 1567.843, 2458.456,  673.885, 8834.15 ])